-- Exercício 2.3 — Espécies
-- Lista com 216 espécies reais, cobrindo todas as categorias e todos os continentes.
-- Os nomes científicos respeitam o CHECK do esquema: 'Genus species'.

INSERT INTO especie (nome_cientifico, nome_comum, categoria, continente) VALUES
    ('Struthio camelus', 'avestruz-comum', 'Aves', 'África'),
    ('Sagittarius serpentarius', 'secretário', 'Aves', 'África'),
    ('Balaeniceps rex', 'bico-de-sapato', 'Aves', 'África'),
    ('Bubo lacteus', 'bufo-de-verreaux', 'Aves', 'África'),
    ('Bucorvus leadbeateri', 'calau-terrestre-do-sul', 'Aves', 'África'),
    ('Psittacus erithacus', 'papagaio-cinzento', 'Aves', 'África'),
    ('Agapornis roseicollis', 'inseparável-de-faces-rosadas', 'Aves', 'África'),
    ('Numida meleagris', 'galinha-da-guiné', 'Aves', 'África'),
    ('Ara macao', 'arara-vermelha', 'Aves', 'América'),
    ('Ramphastos sulfuratus', 'tucano-de-bico-arco-íris', 'Aves', 'América'),
    ('Vultur gryphus', 'condor-dos-andes', 'Aves', 'América'),
    ('Rhea americana', 'ema-comum', 'Aves', 'América'),
    ('Harpia harpyja', 'harpia', 'Aves', 'América'),
    ('Phoenicopterus ruber', 'flamingo-americano', 'Aves', 'América'),
    ('Spheniscus humboldti', 'pinguim-de-humboldt', 'Aves', 'América'),
    ('Pavo cristatus', 'pavão-indiano', 'Aves', 'Asia'),
    ('Grus antigone', 'grou-sarus', 'Aves', 'Asia'),
    ('Buceros bicornis', 'calau-grande', 'Aves', 'Asia'),
    ('Gracula religiosa', 'mainá-religiosa', 'Aves', 'Asia'),
    ('Lophura nycthemera', 'faisão-prateado', 'Aves', 'Asia'),
    ('Copsychus saularis', 'rouxinol-oriental', 'Aves', 'Asia'),
    ('Nipponia nippon', 'íbis-japonês', 'Aves', 'Asia'),
    ('Dromaius novaehollandiae', 'emu', 'Aves', 'Austrália'),
    ('Casuarius casuarius', 'casuar-do-sul', 'Aves', 'Austrália'),
    ('Melopsittacus undulatus', 'periquito-australiano', 'Aves', 'Austrália'),
    ('Eolophus roseicapilla', 'cacatua-galah', 'Aves', 'Austrália'),
    ('Menura novaehollandiae', 'ave-lira-soberba', 'Aves', 'Austrália'),
    ('Trichoglossus moluccanus', 'lóris-arco-íris', 'Aves', 'Austrália'),
    ('Ninox strenua', 'coruja-poderosa', 'Aves', 'Austrália'),
    ('Cygnus olor', 'cisne-mudo', 'Aves', 'Europa'),
    ('Corvus corax', 'corvo-comum', 'Aves', 'Europa'),
    ('Falco peregrinus', 'falcão-peregrino', 'Aves', 'Europa'),
    ('Bubo bubo', 'bufo-real', 'Aves', 'Europa'),
    ('Ciconia ciconia', 'cegonha-branca', 'Aves', 'Europa'),
    ('Erithacus rubecula', 'pisco-de-peito-ruivo', 'Aves', 'Europa'),
    ('Sturnus vulgaris', 'estorninho-comum', 'Aves', 'Europa'),
    ('Panthera leo', 'leão', 'Carnívoros', 'África'),
    ('Panthera pardus', 'leopardo-africano', 'Carnívoros', 'África'),
    ('Acinonyx jubatus', 'chita', 'Carnívoros', 'África'),
    ('Crocuta crocuta', 'hiena-malhada', 'Carnívoros', 'África'),
    ('Lycaon pictus', 'mabeco', 'Carnívoros', 'África'),
    ('Caracal caracal', 'caracal', 'Carnívoros', 'África'),
    ('Leptailurus serval', 'serval', 'Carnívoros', 'África'),
    ('Suricata suricatta', 'suricata', 'Carnívoros', 'África'),
    ('Panthera onca', 'jaguar', 'Carnívoros', 'América'),
    ('Puma concolor', 'puma', 'Carnívoros', 'América'),
    ('Tremarctos ornatus', 'urso-de-óculos', 'Carnívoros', 'América'),
    ('Nasua nasua', 'quati', 'Carnívoros', 'América'),
    ('Procyon lotor', 'guaxinim', 'Carnívoros', 'América'),
    ('Lontra canadensis', 'lontra-norte-americana', 'Carnívoros', 'América'),
    ('Chrysocyon brachyurus', 'lobo-guará', 'Carnívoros', 'América'),
    ('Panthera tigris', 'tigre', 'Carnívoros', 'Asia'),
    ('Panthera uncia', 'leopardo-das-neves', 'Carnívoros', 'Asia'),
    ('Ailurus fulgens', 'panda-vermelho', 'Carnívoros', 'Asia'),
    ('Helarctos malayanus', 'urso-malaio', 'Carnívoros', 'Asia'),
    ('Ursus thibetanus', 'urso-negro-asiático', 'Carnívoros', 'Asia'),
    ('Cuon alpinus', 'cão-selvagem-asiático', 'Carnívoros', 'Asia'),
    ('Prionailurus bengalensis', 'gato-leopardo', 'Carnívoros', 'Asia'),
    ('Canis dingo', 'dingo', 'Carnívoros', 'Austrália'),
    ('Sarcophilus harrisii', 'diabo-da-tasmânia', 'Carnívoros', 'Austrália'),
    ('Dasyurus maculatus', 'quoll-malhado', 'Carnívoros', 'Austrália'),
    ('Dasyurus viverrinus', 'quoll-oriental', 'Carnívoros', 'Austrália'),
    ('Dasyurus hallucatus', 'quoll-do-norte', 'Carnívoros', 'Austrália'),
    ('Antechinus flavipes', 'antequino-de-pés-amarelos', 'Carnívoros', 'Austrália'),
    ('Thylacinus cynocephalus', 'tilacino', 'Carnívoros', 'Austrália'),
    ('Canis lupus', 'lobo-cinzento', 'Carnívoros', 'Europa'),
    ('Vulpes vulpes', 'raposa-vermelha', 'Carnívoros', 'Europa'),
    ('Ursus arctos', 'urso-pardo', 'Carnívoros', 'Europa'),
    ('Lynx lynx', 'lince-euroasiático', 'Carnívoros', 'Europa'),
    ('Meles meles', 'texugo-europeu', 'Carnívoros', 'Europa'),
    ('Martes martes', 'marta-europeia', 'Carnívoros', 'Europa'),
    ('Mustela erminea', 'arminho', 'Carnívoros', 'Europa'),
    ('Loxodonta africana', 'elefante-africano', 'Herbívoros', 'África'),
    ('Giraffa camelopardalis', 'girafa', 'Herbívoros', 'África'),
    ('Hippopotamus amphibius', 'hipopótamo-comum', 'Herbívoros', 'África'),
    ('Diceros bicornis', 'rinoceronte-negro', 'Herbívoros', 'África'),
    ('Ceratotherium simum', 'rinoceronte-branco', 'Herbívoros', 'África'),
    ('Equus quagga', 'zebra-das-planícies', 'Herbívoros', 'África'),
    ('Syncerus caffer', 'búfalo-africano', 'Herbívoros', 'África'),
    ('Tragelaphus strepsiceros', 'cudo-maior', 'Herbívoros', 'África'),
    ('Tapirus terrestris', 'anta-sul-americana', 'Herbívoros', 'América'),
    ('Lama glama', 'lhama', 'Herbívoros', 'América'),
    ('Vicugna vicugna', 'vicunha', 'Herbívoros', 'América'),
    ('Hydrochoerus hydrochaeris', 'capivara', 'Herbívoros', 'América'),
    ('Odocoileus virginianus', 'veado-de-cauda-branca', 'Herbívoros', 'América'),
    ('Bison bison', 'bisão-americano', 'Herbívoros', 'América'),
    ('Mazama americana', 'veado-mateiro', 'Herbívoros', 'América'),
    ('Elephas maximus', 'elefante-asiático', 'Herbívoros', 'Asia'),
    ('Rhinoceros unicornis', 'rinoceronte-indiano', 'Herbívoros', 'Asia'),
    ('Camelus bactrianus', 'camelo-bactriano', 'Herbívoros', 'Asia'),
    ('Bubalus arnee', 'búfalo-selvagem-asiático', 'Herbívoros', 'Asia'),
    ('Bos gaurus', 'gaur', 'Herbívoros', 'Asia'),
    ('Axis axis', 'chital', 'Herbívoros', 'Asia'),
    ('Rusa unicolor', 'sambar', 'Herbívoros', 'Asia'),
    ('Macropus rufus', 'canguru-vermelho', 'Herbívoros', 'Austrália'),
    ('Phascolarctos cinereus', 'coala', 'Herbívoros', 'Austrália'),
    ('Vombatus ursinus', 'vombate-comum', 'Herbívoros', 'Austrália'),
    ('Notamacropus rufogriseus', 'wallaby-de-pescoço-vermelho', 'Herbívoros', 'Austrália'),
    ('Osphranter robustus', 'wallaroo-comum', 'Herbívoros', 'Austrália'),
    ('Lasiorhinus latifrons', 'vombate-de-nariz-peludo', 'Herbívoros', 'Austrália'),
    ('Petrogale penicillata', 'wallaby-das-rochas', 'Herbívoros', 'Austrália'),
    ('Bison bonasus', 'bisão-europeu', 'Herbívoros', 'Europa'),
    ('Capreolus capreolus', 'corço', 'Herbívoros', 'Europa'),
    ('Cervus elaphus', 'veado-vermelho', 'Herbívoros', 'Europa'),
    ('Dama dama', 'gamo', 'Herbívoros', 'Europa'),
    ('Rupicapra rupicapra', 'camurça', 'Herbívoros', 'Europa'),
    ('Ovis aries', 'carneiro-doméstico', 'Herbívoros', 'Europa'),
    ('Capra ibex', 'íbex-dos-alpes', 'Herbívoros', 'Europa'),
    ('Arctocephalus pusillus', 'lobo-marinho-do-cabo', 'Mamíferos Marinhos', 'África'),
    ('Monachus monachus', 'foca-monge-do-mediterrâneo', 'Mamíferos Marinhos', 'África'),
    ('Sousa plumbea', 'golfinho-corcunda-do-índico', 'Mamíferos Marinhos', 'África'),
    ('Delphinus capensis', 'golfinho-comum-de-bico-longo', 'Mamíferos Marinhos', 'África'),
    ('Megaptera novaeangliae', 'baleia-jubarte', 'Mamíferos Marinhos', 'África'),
    ('Eubalaena australis', 'baleia-franca-austral', 'Mamíferos Marinhos', 'África'),
    ('Lagenorhynchus obscurus', 'golfinho-de-peale', 'Mamíferos Marinhos', 'África'),
    ('Zalophus californianus', 'leão-marinho-da-califórnia', 'Mamíferos Marinhos', 'América'),
    ('Mirounga angustirostris', 'elefante-marinho-do-norte', 'Mamíferos Marinhos', 'América'),
    ('Enhydra lutris', 'lontra-marinha', 'Mamíferos Marinhos', 'América'),
    ('Trichechus manatus', 'manatim-das-antilhas', 'Mamíferos Marinhos', 'América'),
    ('Phocoena sinus', 'vaquita', 'Mamíferos Marinhos', 'América'),
    ('Eschrichtius robustus', 'baleia-cinzenta', 'Mamíferos Marinhos', 'América'),
    ('Tursiops truncatus', 'golfinho-roaz', 'Mamíferos Marinhos', 'América'),
    ('Orcinus orca', 'orca', 'Mamíferos Marinhos', 'América'),
    ('Neophocaena phocaenoides', 'toninha-sem-barbatana', 'Mamíferos Marinhos', 'Asia'),
    ('Dugong dugon', 'dugongo', 'Mamíferos Marinhos', 'Asia'),
    ('Lipotes vexillifer', 'baiji', 'Mamíferos Marinhos', 'Asia'),
    ('Platanista gangetica', 'golfinho-do-ganges', 'Mamíferos Marinhos', 'Asia'),
    ('Sousa chinensis', 'golfinho-corcunda-chinês', 'Mamíferos Marinhos', 'Asia'),
    ('Balaenoptera omurai', 'baleia-de-omura', 'Mamíferos Marinhos', 'Asia'),
    ('Pusa sibirica', 'foca-do-baikal', 'Mamíferos Marinhos', 'Asia'),
    ('Neophoca cinerea', 'leão-marinho-australiano', 'Mamíferos Marinhos', 'Austrália'),
    ('Arctocephalus forsteri', 'lobo-marinho-da-nova-zelândia', 'Mamíferos Marinhos', 'Austrália'),
    ('Tursiops aduncus', 'golfinho-roaz-do-índico', 'Mamíferos Marinhos', 'Austrália'),
    ('Balaenoptera musculus', 'baleia-azul', 'Mamíferos Marinhos', 'Austrália'),
    ('Hydrurga leptonyx', 'foca-leopardo', 'Mamíferos Marinhos', 'Austrália'),
    ('Lobodon carcinophaga', 'foca-caranguejeira', 'Mamíferos Marinhos', 'Austrália'),
    ('Leptonychotes weddellii', 'foca-de-weddell', 'Mamíferos Marinhos', 'Austrália'),
    ('Phocoena phocoena', 'toninha-comum', 'Mamíferos Marinhos', 'Europa'),
    ('Halichoerus grypus', 'foca-cinzenta', 'Mamíferos Marinhos', 'Europa'),
    ('Phoca vitulina', 'foca-comum', 'Mamíferos Marinhos', 'Europa'),
    ('Cystophora cristata', 'foca-de-capuz', 'Mamíferos Marinhos', 'Europa'),
    ('Pagophilus groenlandicus', 'foca-da-groenlândia', 'Mamíferos Marinhos', 'Europa'),
    ('Globicephala melas', 'baleia-piloto', 'Mamíferos Marinhos', 'Europa'),
    ('Delphinus delphis', 'golfinho-comum', 'Mamíferos Marinhos', 'Europa'),
    ('Gorilla gorilla', 'gorila-ocidental', 'Primatas', 'África'),
    ('Pan troglodytes', 'chimpanzé-comum', 'Primatas', 'África'),
    ('Pan paniscus', 'bonobo', 'Primatas', 'África'),
    ('Papio anubis', 'babuíno-anúbis', 'Primatas', 'África'),
    ('Mandrillus sphinx', 'mandril', 'Primatas', 'África'),
    ('Cercopithecus mitis', 'macaco-azul', 'Primatas', 'África'),
    ('Colobus guereza', 'colobo-guereza', 'Primatas', 'África'),
    ('Erythrocebus patas', 'macaco-patas', 'Primatas', 'África'),
    ('Chlorocebus pygerythrus', 'macaco-vervet', 'Primatas', 'África'),
    ('Galago senegalensis', 'gálago-do-senegal', 'Primatas', 'África'),
    ('Alouatta caraya', 'bugio-preto', 'Primatas', 'América'),
    ('Cebus capucinus', 'macaco-prego-de-cara-branca', 'Primatas', 'América'),
    ('Saimiri sciureus', 'macaco-de-cheiro', 'Primatas', 'América'),
    ('Ateles geoffroyi', 'macaco-aranha-de-geoffroy', 'Primatas', 'América'),
    ('Callithrix jacchus', 'sagui-comum', 'Primatas', 'América'),
    ('Leontopithecus rosalia', 'mico-leão-dourado', 'Primatas', 'América'),
    ('Aotus trivirgatus', 'macaco-da-noite', 'Primatas', 'América'),
    ('Pithecia pithecia', 'saki-de-cara-branca', 'Primatas', 'América'),
    ('Lagothrix lagotricha', 'macaco-barrigudo', 'Primatas', 'América'),
    ('Saguinus oedipus', 'sagui-cabeça-de-algodão', 'Primatas', 'América'),
    ('Pongo pygmaeus', 'orangotango-de-bornéu', 'Primatas', 'Asia'),
    ('Pongo abelii', 'orangotango-de-sumatra', 'Primatas', 'Asia'),
    ('Macaca mulatta', 'macaco-rhesus', 'Primatas', 'Asia'),
    ('Hylobates lar', 'gibão-de-mãos-brancas', 'Primatas', 'Asia'),
    ('Trachypithecus obscurus', 'langur-escuro', 'Primatas', 'Asia'),
    ('Nasalis larvatus', 'macaco-narigudo', 'Primatas', 'Asia'),
    ('Nycticebus coucang', 'lóris-lento', 'Primatas', 'Asia'),
    ('Symphalangus syndactylus', 'siamang', 'Primatas', 'Asia'),
    ('Hylobates agilis', 'gibão-ágil', 'Primatas', 'Asia'),
    ('Macaca fascicularis', 'macaco-cynomolgus', 'Primatas', 'Asia'),
    ('Macaca fuscata', 'macaco-japonês', 'Primatas', 'Asia'),
    ('Semnopithecus entellus', 'langur-cinzento', 'Primatas', 'Asia'),
    ('Presbytis melalophos', 'surili-de-crista', 'Primatas', 'Asia'),
    ('Tarsius tarsier', 'társio-espectral', 'Primatas', 'Asia'),
    ('Nomascus leucogenys', 'gibão-de-bochechas-brancas', 'Primatas', 'Asia'),
    ('Macaca sylvanus', 'macaco-de-gibraltar', 'Primatas', 'Europa'),
    ('Crocodylus niloticus', 'crocodilo-do-nilo', 'Repteis', 'África'),
    ('Python regius', 'pitão-real', 'Repteis', 'África'),
    ('Varanus niloticus', 'varano-do-nilo', 'Repteis', 'África'),
    ('Centrochelys sulcata', 'tartaruga-sulcata', 'Repteis', 'África'),
    ('Bitis arietans', 'víbora-sopradora', 'Repteis', 'África'),
    ('Dendroaspis polylepis', 'mamba-negra', 'Repteis', 'África'),
    ('Chamaeleo dilepis', 'camaleão-de-pescoço-largo', 'Repteis', 'África'),
    ('Naja haje', 'cobra-egípcia', 'Repteis', 'África'),
    ('Iguana iguana', 'iguana-verde', 'Repteis', 'América'),
    ('Caiman crocodilus', 'jacaré-tinga', 'Repteis', 'América'),
    ('Eunectes murinus', 'sucuri-verde', 'Repteis', 'América'),
    ('Chelonoidis carbonarius', 'jabuti-piranga', 'Repteis', 'América'),
    ('Crotalus durissus', 'cascavel-sul-americana', 'Repteis', 'América'),
    ('Boa constrictor', 'jiboia', 'Repteis', 'América'),
    ('Alligator mississippiensis', 'aligátor-americano', 'Repteis', 'América'),
    ('Python bivittatus', 'pitão-birmanesa', 'Repteis', 'Asia'),
    ('Gavialis gangeticus', 'gavial', 'Repteis', 'Asia'),
    ('Varanus komodoensis', 'dragão-de-komodo', 'Repteis', 'Asia'),
    ('Ophiophagus hannah', 'cobra-rei', 'Repteis', 'Asia'),
    ('Gekko gecko', 'gêco-tokay', 'Repteis', 'Asia'),
    ('Crocodylus porosus', 'crocodilo-de-água-salgada', 'Repteis', 'Asia'),
    ('Testudo horsfieldii', 'tartaruga-russa', 'Repteis', 'Asia'),
    ('Varanus giganteus', 'perentie', 'Repteis', 'Austrália'),
    ('Crocodylus johnstoni', 'crocodilo-de-johnston', 'Repteis', 'Austrália'),
    ('Pogona vitticeps', 'dragão-barbudo', 'Repteis', 'Austrália'),
    ('Morelia spilota', 'pitão-tapete', 'Repteis', 'Austrália'),
    ('Chelodina longicollis', 'tartaruga-de-pescoço-comprido', 'Repteis', 'Austrália'),
    ('Tiliqua scincoides', 'lagarto-de-língua-azul', 'Repteis', 'Austrália'),
    ('Oxyuranus scutellatus', 'taipan-costeiro', 'Repteis', 'Austrália'),
    ('Vipera berus', 'víbora-europeia', 'Repteis', 'Europa'),
    ('Testudo hermanni', 'tartaruga-de-hermann', 'Repteis', 'Europa'),
    ('Lacerta viridis', 'lagarto-verde-europeu', 'Repteis', 'Europa'),
    ('Natrix natrix', 'cobra-de-água', 'Repteis', 'Europa'),
    ('Zamenis longissimus', 'cobra-de-esculápio', 'Repteis', 'Europa'),
    ('Emys orbicularis', 'cágado-europeu', 'Repteis', 'Europa'),
    ('Podarcis muralis', 'lagartixa-dos-muros', 'Repteis', 'Europa');
